name: Kyle Falconer Codes
description: Blog site for kylefalconercodes.com
url: http://blog.kylefalconercodes.com
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
